# params.yaml - Configuration
system:
  num_workers: 1
  gpu:
    strategy: auto
    num_devices: 1
    accelerator: gpu

paths:
  data: /Users/june/Documents/data/tabular_process_param/secom.csv
  results:

preprocessing:
  missing_value: ['mean', 'median', 'drop']
  feature_selection: ['pca', 'mutual_info', 'variance_threshold']
  normalization: ['standard', 'minmax', 'tobust']
  imbalance:
    enable: False
    imbalance_strategy: smote # Choose from ['smote', 'adasyn', 'random_oversampling', 'radom_undersampling']

task:
  type: xgboost #Options: "logistic_regression", "random_forest", "xgboost", "voting_classifier", ....
  hyperparameters:
    logistic_regression:
      C: 1.0
    random_forest:
      n_estimators: 100
    xgboost:
      n_estimators: 100  

plots:
  data_stats: True
  results: True
