# params.yaml - Configuration
system:
  num_workers: 1
  gpu:
    strategy: auto
    num_devices: 1
    accelerator: gpu

paths:
  data:
  results:

preprocessing:
  missing_value_strategy: "mean" # Options: "mean", "median", "most_frequent", "constant", "drop"
  feature_selection: "pca" # Options: "pca", {add more if you have other ideas}
  data_imbalance_strategy: "smote" # Options: "smote", "adasyn", "random_oversampling", "random_undersampling"

task:
  type: xgboost #Options: "logistic_regression", "random_forest", "xgboost", "voting_classifier", {add more if you have other ideas}
  hyperparameters:
    logistic_regression:
      C: 1.0
    random_forest:
      n_estimators: 100
    xgboost:
      n_estimators: 100  

plots:
  data_stats: True
  results: True

params:
  sql_database: "secom"
  missing_value_strategy: "mean"
  feature_selection: "pca"
  normalization: "none"
  model:
    type: "voting_classifier"
    hyperparameters:
      logistic_regression: {}
      random_forest:
        n_estimators: 100
      xgboost: {}
