system:
  datatype: 0  # 0 = tabular, 1 = image


preprocess: 1  # 0 for no preprocessing, 1 for preprocessing

task:
  image:
    train_path: "train"
    test_path: "test"
    valid_path: "valid"
    batch_size: 32
    num_classes: 6
    train_split: 0.8
    image_size: 224

  tabular:
    model_type: 1  # 0 = xgboost, 1 = logistic_regression, 2 = mlp

training:
  feature_selection: 0  # 0 for no feature selection, 1 for feature selection
  use_optuna: 1

model:
  image:
    model_type: 0  # Placeholder for future use (e.g., 0 = ResNet18, 1 = EfficientNet)
  tabular:
    model_type: 1  # 0 = xgboost, 1 = logistic_regression, 2 = mlp

  optuna:
    xgboost:
       n_estimators: [50, 500]
       max_depth: [2, 10]
       learning_rate: [0.01, 0.3]
       subsample: [0.5, 1.0]
       colsample_bytree: [0.5, 1.0]
    logistic_regression:
       C: [0.01, 10.0]

plots:
  data: 0
  results: 0

